version: "3.9"
   
services:
  db:
    image: postgres
    ports: 
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pluragramv2
      - POSTGRES_USER=pluragramv2
      - POSTGRES_PASSWORD=pluragramv2
